<?php
use Fisharebest\Webtrees\I18N;
?>

<!-- markup for media displayed in an iframe-->
  <figure id='node-container'>
    <iframe
      id='node-content'
      sandbox='allow-same-origin allow-scripts'
      allow="layout-animations 'none'; unoptimized-images 'none'; oversized-images 'none'; sync-script 'none'; sync-xhr 'none'; unsized-media 'none';"
    >
      <div class="alert alert-info" role="alert">
        <?= I18N::translate('This browser does not support iframes.') ?><
      /div>
    </iframe>
  </figure>
