<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Auth;
use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Http\RequestHandlers\AddNewFact;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Media;
use Fisharebest\Webtrees\Module\ModuleSidebarInterface;
use Fisharebest\Webtrees\Module\ModuleTabInterface;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var string                             $age
 * @var Collection<Media>                  $individual_media
 * @var Collection<Fact>                   $name_records
 * @var Individual                         $record
 * @var Collection<Fact>                   $sex_records
 * @var Collection<string>                 $shares
 * @var Collection<ModuleSidebarInterface> $sidebars
 * @var Collection<ModuleTabInterface>     $tabs
 * @var Tree                               $tree
 * @var string                             $user_link
 */
?>

<?php if ($individual_media->isNotEmpty() || $tree->getPreference('USE_SILHOUETTE') === '1') : ?>
    <div class="col-sm-3">
        <?php if ($individual_media->isEmpty()) : ?>
            <div class="img-thumbnail">
                <i class="wt-individual-silhouette wt-individual-silhouette-<?= strtolower($record->sex()) ?>"></i>
            </div>
        <?php else : ?>
          <div id="individual-images">
            <div class="active">
                <?= $individual_media->first()->displayImage(200, 260, 'crop', ['class' => 'img-thumbnail img-fluid w-100']) ?>
            </div>
          </div>
        <?php endif ?>

        <?php if (Auth::isEditor($record->tree())) : ?>
            <div class="text-center">
                <a href="<?= e(route(AddNewFact::class, ['tree' => $record->tree()->name(), 'xref' => $record->xref(), 'fact' => 'OBJE'])) ?>">
                    <?= I18N::translate('Add a media object') ?>
                </a>
            </div>
        <?php endif ?>
    </div>
<?php endif ?>
