<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Illuminate\Support\Collection;

/**
 * @var int                  $id
 * @var Collection<stdClass> $rows
 * @var bool                 $show_date
 * @var bool                 $show_user
 */

?>

<?php foreach ($rows as $n => $row) : ?>
    <div class="">
        <a href="<?= e($row->record->url()) ?>">
            <?= $row->record->fullName() ?>
        </a>

        <div class="indent mb-1">
          <?php if ($show_user && $show_date) : ?>
              <?= /* I18N: [a record was] Changed on <date/time> by <user> */I18N::translate('Changed on %1$s by %2$s', view('components/datetime', ['timestamp' => $row->time]), e($row->user->realName())) ?>
          <?php elseif ($show_date) : ?>
              <?= /* I18N: [a record was] Changed on <date/time> */ I18N::translate('Changed on %1$s', view('components/datetime', ['timestamp' => $row->time])) ?>
          <?php elseif ($show_user) : ?>
              <?= /* I18N: [a record was] Changed on <date/time> */ I18N::translate('Changed by %1$s', e($row->user->realName())) ?>
          <?php endif ?>
        </div>
    </div>
<?php endforeach ?>
