<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\View;
use Illuminate\Support\Collection;

/**
 * @var Collection<Fact> $facts
 * @var int              $id
 * @var int              $limit_low
 * @var int              $limit_high
 */

?>

<?php foreach ($facts as $n => $fact) : ?>

    <div class="">
        <?php $record = $fact->record(); ?>
        <a href="<?= e($record->url()) ?>" class="list_item name2">
            <?= $record->fullName() ?>
        </a>
        <?php if ($record instanceof Individual) : ?>
            <?= view('icons/sex', ['sex' => $record->sex()]) ?>
        <?php endif ?>
        <div class="indent">
            <?= $fact->label() . ' — ' . $fact->date()->display($record->tree(), null, true) ?>
            (<?= Registry::timestampFactory()->now()->subtractYears($fact->anniv)->diffForHumans() ?>)
            <?php if ($fact->place()->gedcomName() !== '') : ?>
                — <a href="<?= e($fact->place()->url()) ?>" title="<?= strip_tags($fact->place()->fullName()) ?>">
                    <?= $fact->place()->shortName() ?>
                </a>
            <?php endif ?>
        </div>
    </div>
<?php endforeach ?>
